services:
  postgres:
    image: postgres:16.6
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: strongpassword123
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    volumes:
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak_server
    command:
      [
        "start",
        "--https-certificate-file=/opt/keycloak/certs/cert.pem",
        "--https-certificate-key-file=/opt/keycloak/certs/key.pem",
        "--import-realm",
        "--hostname-strict=false",
      ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: false
      KC_HOSTNAME_URL: https://localhost
      KC_HOSTNAME_ADMIN_URL: https://localhost
    depends_on:
      - postgres
    networks:
      - keycloak-net
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - keycloak-net

volumes:
  postgres_data:

networks:
  keycloak-net:
